// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ugtSjVcwUAaXjsf53GE95cop5qN0H-Y',
    appId: '1:576338515275:web:3d7c059e9364bd01f2c4ce',
    messagingSenderId: '576338515275',
    projectId: 'attendance-demo-1317e',
    authDomain: 'attendance-demo-1317e.firebaseapp.com',
    storageBucket: 'attendance-demo-1317e.firebasestorage.app',
    measurementId: 'G-HQ20B4YRKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Qq3ESrPgvt6zNIx5FeZW2pOsLpvs6hs',
    appId: '1:576338515275:android:30490663487b3fb6f2c4ce',
    messagingSenderId: '576338515275',
    projectId: 'attendance-demo-1317e',
    storageBucket: 'attendance-demo-1317e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatqAS55yhpm857Agif9YeVTYlMX3RfBc',
    appId: '1:576338515275:ios:328113252f184e8df2c4ce',
    messagingSenderId: '576338515275',
    projectId: 'attendance-demo-1317e',
    storageBucket: 'attendance-demo-1317e.firebasestorage.app',
    iosBundleId: 'com.example.attendanceDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAatqAS55yhpm857Agif9YeVTYlMX3RfBc',
    appId: '1:576338515275:ios:328113252f184e8df2c4ce',
    messagingSenderId: '576338515275',
    projectId: 'attendance-demo-1317e',
    storageBucket: 'attendance-demo-1317e.firebasestorage.app',
    iosBundleId: 'com.example.attendanceDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ugtSjVcwUAaXjsf53GE95cop5qN0H-Y',
    appId: '1:576338515275:web:1c5b70c2c5c66a63f2c4ce',
    messagingSenderId: '576338515275',
    projectId: 'attendance-demo-1317e',
    authDomain: 'attendance-demo-1317e.firebaseapp.com',
    storageBucket: 'attendance-demo-1317e.firebasestorage.app',
    measurementId: 'G-K0KZM6SLN1',
  );
}
